### ISSUE TITLE
add template html, css, js to the blog

### ISSUE THREAD

**Issue by alimasyhur** [alimasyhur/mern-blog#1]
add basic template contains html, css, and js files to the blog

**Comment by tejasnopany** [comment]
//Html & Css
<html>
<head>
<title></title>
<style>
     h1{
   color: white;
   background-color: black;
   font-size: 20px;
}
</style>
</head>
<body>
      <h1>This is a heading</h1>
</body>
</html>

**Comment by aleqske** [comment]
Can you kindly elaborate more on this issue.

**Comment by alimasyhur** [comment]
@tejasnopany @alexkimeu0 You might need to read the description clearly
create a PR in order to add basic template contains html, css, and js files to the blog

**Comment by aleqske** [comment]
Ok. I would to tackle it.
